version: "3.8"
services:
    tester:
        build: .
        ports:
            - 10000:10000
        security_opt:
            - seccomp:unconfined
        cap_add:
            - NET_ADMIN
        sysctls:
            - net.core.somaxconn=999999
        volumes:
            - ./config:/usr/go/local
        networks:
            default:
               ipv4_address: 10.100.200.50
#        command: dlv debug 'my5G-RANTester/cmd' --listen=:10000 --headless=true --api-version=2 --log  -- nlinear-tests -s 100 -mu 400 -se 1234565432
#        command: dlv debug 'my5G-RANTester/cmd' --listen=:10000 --headless=true --api-version=2 --log  -- stress-tests -start 10 -end 20 -step 2 -interval 1500
#        command: dlv debug 'my5G-RANTester/cmd' --listen=:10000 --headless=true --api-version=2 --log  -- load-test -n 1
#        command: go run cmd/app.go nlinear-tests -s 100 -mu 400 -se 1234565432
        command: go run cmd/app.go stress-tests -start 10 -end 100 -step 10 -interval 3000
#        command: go run cmd/app.go load-test -n 10 -g
        volumes:
            - ./internal/:/usr/local/go/src/my5G-RANTester/internal
            - ./cmd/:/usr/local/go/src/my5G-RANTester/cmd
            - ./config/:/usr/local/go/src/my5G-RANTester/config
            - ./lib/:/usr/local/go/src/my5G-RANTester/lib
networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 10.100.200.0/24
